language: node_js
node_js: 
  - "10.13.0"

before_install: 
  - export TZ=Europe/Oslo

install:
  - npm install

before_script:
  - npm run checkversions
  - npm run lint
  - npm run postinstall

script:
  - npm run build

before_deploy:
  - npm run build-guideline-app
  - git config --global user.email "ken.aleksander.johansen@nav.no"
  - git config --global user.name "navikt"

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $NAV_DS_TOKEN
    on:
      branch: master
    keep-history: true
    local-dir: "guideline-app/dist"
  - provider: script
    skip-cleanup: true
    on:
      branch: master
    script:
      - npm run build:nodocs && git checkout master && git remote set-url origin https://KenAJoh:$NAV_DS_TOKEN@github.com/navikt/nav-frontend-moduler.git && echo "//registry.npmjs.org/:_authToken=$NAV_DS_NPM_TOKEN" >> ~/.npmrc && npm run lernapublish